-- =====================================================================
-- EDU (edutest.agtci.com) — 01-schema.sql   (PostgreSQL)
-- Full database schema: 50 tables (incl. Laravel "migrations").
-- Generated by database/sql/generate.sh from the Laravel migrations @ 761c3f9
-- with `php artisan migrate --pretend` — the exact SQL `php artisan migrate`
-- runs on PostgreSQL. Needs PostgreSQL 14+ (tested on 16).
--
-- HOW TO IMPORT into an EMPTY database (see database/sql/README.md):
--   psql -v ON_ERROR_STOP=1 -h <host> -U <user> -d <database> -f 01-schema.sql
-- or open it in pgAdmin's Query Tool on that database and run it.
-- No CREATE DATABASE here. Then import 02 (and optionally 03).
--
-- Runs in one transaction: on any error nothing is created.
-- The "migrations" table is filled at the end, so a later
-- `php artisan migrate --force` on the server is a no-op, not an error.
-- DO NOT import into a database that already has these tables.
-- =====================================================================

SET client_encoding = 'UTF8';
SET search_path = public;

BEGIN;

create table "migrations" ("id" serial not null primary key, "migration" varchar(255) not null, "batch" integer not null);

-- 0001_01_01_000000_create_users_table
create table "users" ("id" bigserial not null primary key, "name" varchar(255) not null, "email" varchar(255) not null, "email_verified_at" timestamp(0) without time zone null, "password" varchar(255) not null, "remember_token" varchar(100) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "users" add constraint "users_email_unique" unique ("email");
create table "password_reset_tokens" ("email" varchar(255) not null, "token" varchar(255) not null, "created_at" timestamp(0) without time zone null);
alter table "password_reset_tokens" add primary key ("email");
create table "sessions" ("id" varchar(255) not null, "user_id" bigint null, "ip_address" varchar(45) null, "user_agent" text null, "payload" text not null, "last_activity" integer not null);
alter table "sessions" add primary key ("id");
create index "sessions_user_id_index" on "sessions" ("user_id");
create index "sessions_last_activity_index" on "sessions" ("last_activity");

-- 0001_01_01_000001_create_cache_table
create table "cache" ("key" varchar(255) not null, "value" text not null, "expiration" bigint not null);
alter table "cache" add primary key ("key");
create index "cache_expiration_index" on "cache" ("expiration");
create table "cache_locks" ("key" varchar(255) not null, "owner" varchar(255) not null, "expiration" bigint not null);
alter table "cache_locks" add primary key ("key");
create index "cache_locks_expiration_index" on "cache_locks" ("expiration");

-- 0001_01_01_000002_create_jobs_table
create table "jobs" ("id" bigserial not null primary key, "queue" varchar(255) not null, "payload" text not null, "attempts" smallint not null, "reserved_at" integer null, "available_at" integer not null, "created_at" integer not null);
create index "jobs_queue_index" on "jobs" ("queue");
create table "job_batches" ("id" varchar(255) not null, "name" varchar(255) not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text null, "cancelled_at" integer null, "created_at" integer not null, "finished_at" integer null);
alter table "job_batches" add primary key ("id");
create table "failed_jobs" ("id" bigserial not null primary key, "uuid" varchar(255) not null, "connection" varchar(255) not null, "queue" varchar(255) not null, "payload" text not null, "exception" text not null, "failed_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP);
create index "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
alter table "failed_jobs" add constraint "failed_jobs_uuid_unique" unique ("uuid");

-- 2026_08_25_011344_create_permission_tables
create table "permissions" ("id" bigserial not null primary key, "name" varchar(255) not null, "guard_name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "permissions" add constraint "permissions_name_guard_name_unique" unique ("name", "guard_name");
create table "roles" ("id" bigserial not null primary key, "name" varchar(255) not null, "guard_name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "roles" add constraint "roles_name_guard_name_unique" unique ("name", "guard_name");
create table "model_has_permissions" ("permission_id" bigint not null, "model_type" varchar(255) not null, "model_id" bigint not null);
create index "model_has_permissions_model_id_model_type_index" on "model_has_permissions" ("model_id", "model_type");
alter table "model_has_permissions" add constraint "model_has_permissions_permission_id_foreign" foreign key ("permission_id") references "permissions" ("id") on delete cascade;
alter table "model_has_permissions" add primary key ("permission_id", "model_id", "model_type");
create table "model_has_roles" ("role_id" bigint not null, "model_type" varchar(255) not null, "model_id" bigint not null);
create index "model_has_roles_model_id_model_type_index" on "model_has_roles" ("model_id", "model_type");
alter table "model_has_roles" add constraint "model_has_roles_role_id_foreign" foreign key ("role_id") references "roles" ("id") on delete cascade;
alter table "model_has_roles" add primary key ("role_id", "model_id", "model_type");
create table "role_has_permissions" ("permission_id" bigint not null, "role_id" bigint not null);
alter table "role_has_permissions" add constraint "role_has_permissions_permission_id_foreign" foreign key ("permission_id") references "permissions" ("id") on delete cascade;
alter table "role_has_permissions" add constraint "role_has_permissions_role_id_foreign" foreign key ("role_id") references "roles" ("id") on delete cascade;
alter table "role_has_permissions" add primary key ("permission_id", "role_id");
delete from "cache" where "key" in ('education-accountability-platform-cache-spatie.permission.cache', 'education-accountability-platform-cache-illuminate:cache:flexible:created:spatie.permission.cache');

-- 2026_08_25_044125_create_states_table
create table "states" ("id" bigserial not null primary key, "name" varchar(255) not null, "code" varchar(10) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "states" add constraint "states_code_unique" unique ("code");

-- 2026_08_25_044126_create_districts_table
create table "districts" ("id" bigserial not null primary key, "state_id" bigint not null, "name" varchar(255) not null, "code" varchar(20) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "districts" add constraint "districts_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete cascade;
alter table "districts" add constraint "districts_state_id_name_unique" unique ("state_id", "name");

-- 2026_08_25_044127_create_schools_table
create table "schools" ("id" bigserial not null primary key, "school_code" varchar(255) not null, "name" varchar(255) not null, "board" varchar(255) check ("board" in ('CBSE', 'ICSE', 'STATE', 'IB', 'OTHER')) not null default 'STATE', "management_type" varchar(255) check ("management_type" in ('government', 'aided', 'private', 'international')) not null default 'private', "state_id" bigint not null, "district_id" bigint not null, "address" varchar(255) not null, "city" varchar(255) not null, "pincode" varchar(10) not null, "phone" varchar(255) null, "email" varchar(255) null, "website" varchar(255) null, "recognition_status" varchar(255) check ("recognition_status" in ('verified', 'pending', 'under_review')) not null default 'pending', "classes_from" varchar(20) null, "classes_to" varchar(20) null, "student_count" integer not null default '0', "teacher_count" integer not null default '0', "established_year" smallint null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "schools" add constraint "schools_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete restrict;
alter table "schools" add constraint "schools_district_id_foreign" foreign key ("district_id") references "districts" ("id") on delete restrict;
create index "schools_state_id_district_id_index" on "schools" ("state_id", "district_id");
create index "schools_name_index" on "schools" ("name");
create index "schools_pincode_index" on "schools" ("pincode");
create index "schools_board_index" on "schools" ("board");
alter table "schools" add constraint "schools_school_code_unique" unique ("school_code");

-- 2026_08_25_044128_create_school_profiles_table
create table "school_profiles" ("id" bigserial not null primary key, "school_id" bigint not null, "about" text null, "facilities" json null, "sports" json null, "fees" json null, "policies" text null, "has_transport" boolean not null default '0', "has_hostel" boolean not null default '0', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "school_profiles" add constraint "school_profiles_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "school_profiles" add constraint "school_profiles_school_id_unique" unique ("school_id");

-- 2026_08_25_044129_create_anonymous_identities_table
create table "anonymous_identities" ("id" bigserial not null primary key, "user_id" bigint not null, "school_id" bigint not null, "context" varchar(255) check ("context" in ('parent', 'student')) not null, "anonymous_ref" varchar(40) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "anonymous_identities" add constraint "anonymous_identities_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "anonymous_identities" add constraint "anonymous_identities_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "anonymous_identities" add constraint "anon_identity_unique" unique ("user_id", "school_id", "context");
alter table "anonymous_identities" add constraint "anonymous_identities_anonymous_ref_unique" unique ("anonymous_ref");

-- 2026_08_25_044130_create_parent_profiles_table
create table "parent_profiles" ("id" bigserial not null primary key, "user_id" bigint not null, "phone" varchar(20) null, "verified_at" timestamp(0) without time zone null, "verification_method" varchar(40) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "parent_profiles" add constraint "parent_profiles_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "parent_profiles" add constraint "parent_profiles_user_id_unique" unique ("user_id");

-- 2026_08_25_044131_create_student_profiles_table
create table "student_profiles" ("id" bigserial not null primary key, "user_id" bigint not null, "date_of_birth" date null, "gender" varchar(20) null, "verified_at" timestamp(0) without time zone null, "verification_method" varchar(40) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "student_profiles" add constraint "student_profiles_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "student_profiles" add constraint "student_profiles_user_id_unique" unique ("user_id");

-- 2026_08_25_044132_create_teacher_profiles_table
create table "teacher_profiles" ("id" bigserial not null primary key, "user_id" bigint not null, "subject_specialization" varchar(255) null, "qualification" varchar(255) null, "joining_date" date null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "teacher_profiles" add constraint "teacher_profiles_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "teacher_profiles" add constraint "teacher_profiles_user_id_unique" unique ("user_id");

-- 2026_08_25_044133_create_school_staff_table
create table "school_staff" ("id" bigserial not null primary key, "user_id" bigint not null, "school_id" bigint not null, "designation" varchar(60) not null default 'School Admin', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "school_staff" add constraint "school_staff_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "school_staff" add constraint "school_staff_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "school_staff" add constraint "school_staff_user_id_school_id_unique" unique ("user_id", "school_id");

-- 2026_08_25_044134_create_parent_school_relationships_table
create table "parent_school_relationships" ("id" bigserial not null primary key, "user_id" bigint not null, "school_id" bigint not null, "student_user_id" bigint null, "status" varchar(255) check ("status" in ('pending', 'verified', 'rejected')) not null default 'pending', "verified_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "parent_school_relationships" add constraint "parent_school_relationships_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "parent_school_relationships" add constraint "parent_school_relationships_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "parent_school_relationships" add constraint "parent_school_relationships_student_user_id_foreign" foreign key ("student_user_id") references "users" ("id") on delete set null;
alter table "parent_school_relationships" add constraint "parent_school_rel_unique" unique ("user_id", "school_id", "student_user_id");

-- 2026_08_25_044135_create_student_school_relationships_table
create table "student_school_relationships" ("id" bigserial not null primary key, "user_id" bigint not null, "school_id" bigint not null, "class_grade" varchar(20) null, "status" varchar(255) check ("status" in ('pending', 'verified', 'rejected')) not null default 'pending', "verified_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "student_school_relationships" add constraint "student_school_relationships_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "student_school_relationships" add constraint "student_school_relationships_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "student_school_relationships" add constraint "student_school_relationships_user_id_school_id_unique" unique ("user_id", "school_id");

-- 2026_08_25_044136_create_teacher_school_relationships_table
create table "teacher_school_relationships" ("id" bigserial not null primary key, "user_id" bigint not null, "school_id" bigint not null, "status" varchar(255) check ("status" in ('pending', 'verified', 'rejected')) not null default 'pending', "verified_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "teacher_school_relationships" add constraint "teacher_school_relationships_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "teacher_school_relationships" add constraint "teacher_school_relationships_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "teacher_school_relationships" add constraint "teacher_school_relationships_user_id_school_id_unique" unique ("user_id", "school_id");

-- 2026_08_25_044137_create_complaint_categories_table
create table "complaint_categories" ("id" bigserial not null primary key, "name" varchar(255) not null, "slug" varchar(255) not null, "description" text null, "is_child_safety" boolean not null default '0', "is_active" boolean not null default '1', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "complaint_categories" add constraint "complaint_categories_slug_unique" unique ("slug");

-- 2026_08_25_044138_create_complaints_table
create table "complaints" ("id" bigserial not null primary key, "complaint_number" varchar(40) not null, "school_id" bigint not null, "complaint_category_id" bigint not null, "district_id" bigint not null, "state_id" bigint not null, "anonymous_ref" varchar(40) not null, "submitted_role" varchar(255) check ("submitted_role" in ('parent', 'student')) not null, "subject" varchar(255) not null, "description" text not null, "severity" varchar(255) check ("severity" in ('low', 'medium', 'high', 'critical')) not null default 'medium', "status" varchar(255) check ("status" in ('submitted', 'under_review', 'school_responded', 'escalated', 'investigating', 'action_taken', 'resolved', 'closed')) not null default 'submitted', "is_child_safety_flag" boolean not null default '0', "resolved_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "complaints" add constraint "complaints_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete restrict;
alter table "complaints" add constraint "complaints_complaint_category_id_foreign" foreign key ("complaint_category_id") references "complaint_categories" ("id") on delete restrict;
alter table "complaints" add constraint "complaints_district_id_foreign" foreign key ("district_id") references "districts" ("id") on delete restrict;
alter table "complaints" add constraint "complaints_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete restrict;
create index "complaints_status_index" on "complaints" ("status");
create index "complaints_anonymous_ref_index" on "complaints" ("anonymous_ref");
create index "complaints_school_id_status_index" on "complaints" ("school_id", "status");
create index "complaints_district_id_status_index" on "complaints" ("district_id", "status");
alter table "complaints" add constraint "complaints_complaint_number_unique" unique ("complaint_number");

-- 2026_08_25_044139_create_complaint_evidence_table
create table "complaint_evidence" ("id" bigserial not null primary key, "complaint_id" bigint not null, "uploaded_by" varchar(255) check ("uploaded_by" in ('submitter', 'school')) not null default 'submitter', "original_filename" varchar(255) not null, "stored_filename" varchar(255) not null, "mime_type" varchar(100) not null, "size_bytes" bigint not null, "disk" varchar(40) not null default 'local', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "complaint_evidence" add constraint "complaint_evidence_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete cascade;

-- 2026_08_25_044140_create_complaint_responses_table
create table "complaint_responses" ("id" bigserial not null primary key, "complaint_id" bigint not null, "responder_type" varchar(255) check ("responder_type" in ('school', 'district', 'state')) not null, "responder_user_id" bigint null, "message" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "complaint_responses" add constraint "complaint_responses_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete cascade;
alter table "complaint_responses" add constraint "complaint_responses_responder_user_id_foreign" foreign key ("responder_user_id") references "users" ("id") on delete set null;

-- 2026_08_25_044141_create_complaint_status_history_table
create table "complaint_status_history" ("id" bigserial not null primary key, "complaint_id" bigint not null, "from_status" varchar(40) null, "to_status" varchar(40) not null, "changed_by_user_id" bigint null, "note" text null, "created_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP);
alter table "complaint_status_history" add constraint "complaint_status_history_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete cascade;
alter table "complaint_status_history" add constraint "complaint_status_history_changed_by_user_id_foreign" foreign key ("changed_by_user_id") references "users" ("id") on delete set null;

-- 2026_08_25_044142_create_complaint_resolutions_table
create table "complaint_resolutions" ("id" bigserial not null primary key, "complaint_id" bigint not null, "resolution_summary" text null, "confirmed_by_submitter" varchar(255) check ("confirmed_by_submitter" in ('pending', 'yes', 'partially', 'no')) not null default 'pending', "confirmed_at" timestamp(0) without time zone null, "escalated" boolean not null default '0', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "complaint_resolutions" add constraint "complaint_resolutions_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete cascade;
alter table "complaint_resolutions" add constraint "complaint_resolutions_complaint_id_unique" unique ("complaint_id");

-- 2026_08_25_044143_create_school_feedback_table
create table "school_feedback" ("id" bigserial not null primary key, "school_id" bigint not null, "anonymous_ref" varchar(40) not null, "rater_role" varchar(255) check ("rater_role" in ('parent', 'student')) not null, "dimension_scores" json not null, "overall_comment" text null, "submitted_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "school_feedback" add constraint "school_feedback_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
create index "school_feedback_school_id_submitted_at_index" on "school_feedback" ("school_id", "submitted_at");
create index "school_feedback_anonymous_ref_index" on "school_feedback" ("anonymous_ref");

-- 2026_08_25_044144_create_school_rating_components_table
create table "school_rating_components" ("id" bigserial not null primary key, "key" varchar(60) not null, "label" varchar(255) not null, "weight" decimal(5, 2) not null default '10', "is_active" boolean not null default '1', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "school_rating_components" add constraint "school_rating_components_key_unique" unique ("key");

-- 2026_08_25_044145_create_school_quality_scores_table
create table "school_quality_scores" ("id" bigserial not null primary key, "school_id" bigint not null, "score" decimal(5, 2) not null, "confidence" varchar(255) check ("confidence" in ('high', 'medium', 'low', 'insufficient_data')) not null, "response_count" integer not null, "component_breakdown" json not null, "calculated_at" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "school_quality_scores" add constraint "school_quality_scores_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
create index "school_quality_scores_school_id_calculated_at_index" on "school_quality_scores" ("school_id", "calculated_at");

-- 2026_08_25_044146_create_audit_logs_table
create table "audit_logs" ("id" bigserial not null primary key, "user_id" bigint null, "action" varchar(80) not null, "auditable_type" varchar(255) null, "auditable_id" bigint null, "ip_address" varchar(45) null, "metadata" json null, "created_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP);
alter table "audit_logs" add constraint "audit_logs_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete set null;
create index "audit_logs_auditable_type_auditable_id_index" on "audit_logs" ("auditable_type", "auditable_id");
create index "audit_logs_action_index" on "audit_logs" ("action");

-- 2026_08_25_044147_create_identity_access_logs_table
create table "identity_access_logs" ("id" bigserial not null primary key, "officer_user_id" bigint not null, "anonymous_ref" varchar(40) not null, "action" varchar(80) not null, "reason" text null, "created_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP);
alter table "identity_access_logs" add constraint "identity_access_logs_officer_user_id_foreign" foreign key ("officer_user_id") references "users" ("id") on delete restrict;
create index "identity_access_logs_anonymous_ref_index" on "identity_access_logs" ("anonymous_ref");
create index "identity_access_logs_officer_user_id_index" on "identity_access_logs" ("officer_user_id");

-- 2026_08_25_044148_create_notifications_table
create table "notifications" ("id" uuid not null, "type" varchar(255) not null, "notifiable_type" varchar(255) not null, "notifiable_id" bigint not null, "data" text not null, "read_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create index "notifications_notifiable_type_notifiable_id_index" on "notifications" ("notifiable_type", "notifiable_id");
alter table "notifications" add primary key ("id");

-- 2026_08_25_044427_create_officer_jurisdictions_table
create table "officer_jurisdictions" ("id" bigserial not null primary key, "user_id" bigint not null, "level" varchar(255) check ("level" in ('district', 'state', 'national')) not null, "district_id" bigint null, "state_id" bigint null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "officer_jurisdictions" add constraint "officer_jurisdictions_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "officer_jurisdictions" add constraint "officer_jurisdictions_district_id_foreign" foreign key ("district_id") references "districts" ("id") on delete cascade;
alter table "officer_jurisdictions" add constraint "officer_jurisdictions_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete cascade;
alter table "officer_jurisdictions" add constraint "officer_jurisdiction_unique" unique ("user_id", "level", "district_id", "state_id");

-- 2026_08_26_023118_create_retaliation_reports_table
create table "retaliation_reports" ("id" bigserial not null primary key, "complaint_id" bigint null, "school_id" bigint not null, "district_id" bigint not null, "state_id" bigint not null, "anonymous_ref" varchar(40) not null, "submitted_role" varchar(255) check ("submitted_role" in ('parent', 'student')) not null, "category" varchar(255) check ("category" in ('intimidation', 'harassment', 'discrimination', 'punishment', 'academic_retaliation', 'threats', 'withdrawal_of_facilities', 'other')) not null, "description" text not null, "status" varchar(255) check ("status" in ('submitted', 'under_review', 'investigating', 'action_taken', 'resolved', 'closed')) not null default 'submitted', "resolved_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "retaliation_reports" add constraint "retaliation_reports_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete set null;
alter table "retaliation_reports" add constraint "retaliation_reports_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete restrict;
alter table "retaliation_reports" add constraint "retaliation_reports_district_id_foreign" foreign key ("district_id") references "districts" ("id") on delete restrict;
alter table "retaliation_reports" add constraint "retaliation_reports_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete restrict;
create index "retaliation_reports_status_index" on "retaliation_reports" ("status");
create index "retaliation_reports_anonymous_ref_index" on "retaliation_reports" ("anonymous_ref");
create index "retaliation_reports_district_id_status_index" on "retaliation_reports" ("district_id", "status");

-- 2026_08_26_023130_create_teacher_feedback_table
create table "teacher_feedback" ("id" bigserial not null primary key, "teacher_user_id" bigint not null, "school_id" bigint not null, "anonymous_ref" varchar(40) not null, "rater_role" varchar(255) check ("rater_role" in ('parent', 'student')) not null, "dimension_scores" json not null, "overall_comment" text null, "submitted_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "teacher_feedback" add constraint "teacher_feedback_teacher_user_id_foreign" foreign key ("teacher_user_id") references "users" ("id") on delete cascade;
alter table "teacher_feedback" add constraint "teacher_feedback_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
create index "teacher_feedback_teacher_user_id_submitted_at_index" on "teacher_feedback" ("teacher_user_id", "submitted_at");
create index "teacher_feedback_anonymous_ref_index" on "teacher_feedback" ("anonymous_ref");

-- 2026_08_26_023143_create_teacher_effectiveness_scores_table
create table "teacher_effectiveness_scores" ("id" bigserial not null primary key, "teacher_user_id" bigint not null, "score" decimal(5, 2) not null, "confidence" varchar(255) check ("confidence" in ('high', 'medium', 'low', 'insufficient_data')) not null, "response_count" integer not null, "component_breakdown" json not null, "calculated_at" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "teacher_effectiveness_scores" add constraint "teacher_effectiveness_scores_teacher_user_id_foreign" foreign key ("teacher_user_id") references "users" ("id") on delete cascade;
create index "teacher_effectiveness_scores_teacher_user_id_calculated_at_index" on "teacher_effectiveness_scores" ("teacher_user_id", "calculated_at");

-- 2026_08_26_024026_create_teacher_rating_components_table
create table "teacher_rating_components" ("id" bigserial not null primary key, "key" varchar(60) not null, "label" varchar(255) not null, "weight" decimal(5, 2) not null default '10', "is_active" boolean not null default '1', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "teacher_rating_components" add constraint "teacher_rating_components_key_unique" unique ("key");

-- 2026_08_26_071443_create_invitations_table
create table "invitations" ("id" bigserial not null primary key, "school_id" bigint not null, "invited_by_user_id" bigint not null, "email" varchar(255) not null, "role" varchar(255) check ("role" in ('parent', 'student', 'teacher')) not null, "student_name" varchar(255) null, "token" varchar(64) not null, "status" varchar(255) check ("status" in ('pending', 'accepted', 'revoked')) not null default 'pending', "accepted_by_user_id" bigint null, "accepted_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "invitations" add constraint "invitations_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "invitations" add constraint "invitations_invited_by_user_id_foreign" foreign key ("invited_by_user_id") references "users" ("id") on delete cascade;
alter table "invitations" add constraint "invitations_accepted_by_user_id_foreign" foreign key ("accepted_by_user_id") references "users" ("id") on delete set null;
create index "invitations_school_id_status_index" on "invitations" ("school_id", "status");
alter table "invitations" add constraint "invitations_token_unique" unique ("token");

-- 2026_08_26_134827_create_student_academic_records_table
create table "student_academic_records" ("id" bigserial not null primary key, "student_user_id" bigint not null, "school_id" bigint not null, "subject" varchar(100) not null, "term" varchar(40) not null, "score" decimal(6, 2) not null, "max_score" decimal(6, 2) not null default '100', "recorded_by_user_id" bigint not null, "recorded_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "student_academic_records" add constraint "student_academic_records_student_user_id_foreign" foreign key ("student_user_id") references "users" ("id") on delete cascade;
alter table "student_academic_records" add constraint "student_academic_records_school_id_foreign" foreign key ("school_id") references "schools" ("id") on delete cascade;
alter table "student_academic_records" add constraint "student_academic_records_recorded_by_user_id_foreign" foreign key ("recorded_by_user_id") references "users" ("id") on delete restrict;
create index "student_academic_records_student_user_id_subject_index" on "student_academic_records" ("student_user_id", "subject");
create index "student_academic_records_school_id_subject_term_index" on "student_academic_records" ("school_id", "subject", "term");

-- 2026_08_26_134833_create_fraud_flags_table
create table "fraud_flags" ("id" bigserial not null primary key, "flag_type" varchar(255) check ("flag_type" in ('feedback_spike', 'coordinated_review', 'duplicate_pattern', 'other')) not null, "subject_type" varchar(255) check ("subject_type" in ('school', 'teacher')) not null, "subject_id" bigint not null, "details" json null, "status" varchar(255) check ("status" in ('open', 'reviewing', 'dismissed', 'confirmed')) not null default 'open', "reviewed_by_user_id" bigint null, "reviewed_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "fraud_flags" add constraint "fraud_flags_reviewed_by_user_id_foreign" foreign key ("reviewed_by_user_id") references "users" ("id") on delete set null;
create index "fraud_flags_subject_type_subject_id_index" on "fraud_flags" ("subject_type", "subject_id");
create index "fraud_flags_status_index" on "fraud_flags" ("status");

-- 2026_08_26_134834_create_appeals_table
create table "appeals" ("id" bigserial not null primary key, "complaint_id" bigint not null, "district_id" bigint not null, "state_id" bigint not null, "anonymous_ref" varchar(40) not null, "reason" text not null, "status" varchar(255) check ("status" in ('submitted', 'under_review', 'upheld', 'denied')) not null default 'submitted', "reviewed_by_user_id" bigint null, "decision_note" text null, "resolved_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "appeals" add constraint "appeals_complaint_id_foreign" foreign key ("complaint_id") references "complaints" ("id") on delete cascade;
alter table "appeals" add constraint "appeals_district_id_foreign" foreign key ("district_id") references "districts" ("id") on delete restrict;
alter table "appeals" add constraint "appeals_state_id_foreign" foreign key ("state_id") references "states" ("id") on delete restrict;
alter table "appeals" add constraint "appeals_reviewed_by_user_id_foreign" foreign key ("reviewed_by_user_id") references "users" ("id") on delete set null;
alter table "appeals" add constraint "appeals_complaint_id_unique" unique ("complaint_id");
create index "appeals_status_index" on "appeals" ("status");
create index "appeals_state_id_status_index" on "appeals" ("state_id", "status");

-- 2026_08_26_134838_create_analytics_snapshots_table
create table "analytics_snapshots" ("id" bigserial not null primary key, "scope" varchar(255) check ("scope" in ('state', 'national')) not null, "scope_id" bigint null, "metrics" json not null, "calculated_at" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create index "analytics_snapshots_scope_scope_id_calculated_at_index" on "analytics_snapshots" ("scope", "scope_id", "calculated_at");

-- 2026_08_26_134839_create_two_factor_authentications_table
create table "two_factor_authentications" ("id" bigserial not null primary key, "user_id" bigint not null, "secret" text not null, "recovery_codes" text null, "confirmed_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "two_factor_authentications" add constraint "two_factor_authentications_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade;
alter table "two_factor_authentications" add constraint "two_factor_authentications_user_id_unique" unique ("user_id");

-- 2026_08_26_134840_create_settings_table
create table "settings" ("id" bigserial not null primary key, "key" varchar(100) not null, "value" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "settings" add constraint "settings_key_unique" unique ("key");

-- Record every migration as applied (batch 1)
INSERT INTO "migrations" ("migration", "batch") VALUES
  ('0001_01_01_000000_create_users_table', 1),
  ('0001_01_01_000001_create_cache_table', 1),
  ('0001_01_01_000002_create_jobs_table', 1),
  ('2026_08_25_011344_create_permission_tables', 1),
  ('2026_08_25_044125_create_states_table', 1),
  ('2026_08_25_044126_create_districts_table', 1),
  ('2026_08_25_044127_create_schools_table', 1),
  ('2026_08_25_044128_create_school_profiles_table', 1),
  ('2026_08_25_044129_create_anonymous_identities_table', 1),
  ('2026_08_25_044130_create_parent_profiles_table', 1),
  ('2026_08_25_044131_create_student_profiles_table', 1),
  ('2026_08_25_044132_create_teacher_profiles_table', 1),
  ('2026_08_25_044133_create_school_staff_table', 1),
  ('2026_08_25_044134_create_parent_school_relationships_table', 1),
  ('2026_08_25_044135_create_student_school_relationships_table', 1),
  ('2026_08_25_044136_create_teacher_school_relationships_table', 1),
  ('2026_08_25_044137_create_complaint_categories_table', 1),
  ('2026_08_25_044138_create_complaints_table', 1),
  ('2026_08_25_044139_create_complaint_evidence_table', 1),
  ('2026_08_25_044140_create_complaint_responses_table', 1),
  ('2026_08_25_044141_create_complaint_status_history_table', 1),
  ('2026_08_25_044142_create_complaint_resolutions_table', 1),
  ('2026_08_25_044143_create_school_feedback_table', 1),
  ('2026_08_25_044144_create_school_rating_components_table', 1),
  ('2026_08_25_044145_create_school_quality_scores_table', 1),
  ('2026_08_25_044146_create_audit_logs_table', 1),
  ('2026_08_25_044147_create_identity_access_logs_table', 1),
  ('2026_08_25_044148_create_notifications_table', 1),
  ('2026_08_25_044427_create_officer_jurisdictions_table', 1),
  ('2026_08_26_023118_create_retaliation_reports_table', 1),
  ('2026_08_26_023130_create_teacher_feedback_table', 1),
  ('2026_08_26_023143_create_teacher_effectiveness_scores_table', 1),
  ('2026_08_26_024026_create_teacher_rating_components_table', 1),
  ('2026_08_26_071443_create_invitations_table', 1),
  ('2026_08_26_134827_create_student_academic_records_table', 1),
  ('2026_08_26_134833_create_fraud_flags_table', 1),
  ('2026_08_26_134834_create_appeals_table', 1),
  ('2026_08_26_134838_create_analytics_snapshots_table', 1),
  ('2026_08_26_134839_create_two_factor_authentications_table', 1),
  ('2026_08_26_134840_create_settings_table', 1);

COMMIT;
