-- =====================================================================
-- EDU — 02-reference-data.sql   (PostgreSQL)
-- Reference data every environment needs, generated by
-- database/sql/generate.sh from the app's own seeders @ 761c3f9:
-- 10 roles, 11 permissions + 30 role grants (spatie),
-- 3 states, 5 districts, 22 complaint categories, 10 school and
-- 12 teacher rating components.
-- Import AFTER 01-schema.sql into the same database. ON CONFLICT DO
-- NOTHING, so re-importing is harmless. Creates NO user accounts — see 03.
-- =====================================================================

SET client_encoding = 'UTF8';
SET search_path = public;

BEGIN;

INSERT INTO public.complaint_categories (id, name, slug, description, is_child_safety, is_active, created_at, updated_at) VALUES
	(1, 'Teaching', 'teaching', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(2, 'Teacher Behaviour', 'teacher-behaviour', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(3, 'Fees', 'fees', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(4, 'Books', 'books', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(5, 'Uniform', 'uniform', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(6, 'Stationery', 'stationery', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(7, 'Transport', 'transport', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(8, 'Infrastructure', 'infrastructure', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(9, 'Safety', 'safety', NULL, true, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(10, 'Bullying', 'bullying', NULL, true, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(11, 'Harassment', 'harassment', NULL, true, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(12, 'Discrimination', 'discrimination', NULL, true, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(13, 'Food', 'food', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(14, 'Hygiene', 'hygiene', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(15, 'Sports', 'sports', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(16, 'Counselling', 'counselling', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(17, 'Special Needs', 'special-needs', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(18, 'Attendance', 'attendance', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(19, 'Communication', 'communication', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(20, 'Management', 'management', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(21, 'Career Guidance', 'career-guidance', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(22, 'Other', 'other', NULL, false, true, '2026-10-09 21:18:43', '2026-10-09 21:18:43') ON CONFLICT DO NOTHING;

INSERT INTO public.states (id, name, code, created_at, updated_at) VALUES
	(1, 'Maharashtra', 'MH', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(2, 'Karnataka', 'KA', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(3, 'Delhi', 'DL', '2026-10-09 21:18:43', '2026-10-09 21:18:43') ON CONFLICT DO NOTHING;

INSERT INTO public.districts (id, state_id, name, code, created_at, updated_at) VALUES
	(1, 1, 'Pune', 'PUN', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(2, 1, 'Mumbai', 'MUM', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(3, 2, 'Bengaluru Urban', 'BLR', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(4, 2, 'Mysuru', 'MYS', '2026-10-09 21:18:43', '2026-10-09 21:18:43'),
	(5, 3, 'New Delhi', 'NDL', '2026-10-09 21:18:43', '2026-10-09 21:18:43') ON CONFLICT DO NOTHING;

INSERT INTO public.permissions (id, name, guard_name, created_at, updated_at) VALUES
	(1, 'submit-complaint', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(2, 'submit-feedback', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(3, 'view-own-complaints', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(4, 'respond-to-complaint', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(5, 'manage-school-profile', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(6, 'review-district-complaints', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(7, 'review-state-complaints', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(8, 'access-protected-identity', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(9, 'view-audit-logs', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(10, 'manage-admin-settings', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(11, 'view-national-analytics', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42') ON CONFLICT DO NOTHING;

INSERT INTO public.roles (id, name, guard_name, created_at, updated_at) VALUES
	(1, 'public', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(2, 'parent', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(3, 'student', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(4, 'teacher', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(5, 'school_admin', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(6, 'district_officer', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(7, 'state_officer', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(8, 'national_admin', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(9, 'researcher', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42'),
	(10, 'system_admin', 'web', '2026-10-09 21:18:42', '2026-10-09 21:18:42') ON CONFLICT DO NOTHING;

INSERT INTO public.role_has_permissions (permission_id, role_id) VALUES
	(1, 2),
	(2, 2),
	(3, 2),
	(1, 3),
	(2, 3),
	(3, 3),
	(3, 4),
	(4, 5),
	(5, 5),
	(6, 6),
	(8, 6),
	(7, 7),
	(8, 7),
	(11, 7),
	(7, 8),
	(8, 8),
	(9, 8),
	(11, 8),
	(11, 9),
	(1, 10),
	(2, 10),
	(3, 10),
	(4, 10),
	(5, 10),
	(6, 10),
	(7, 10),
	(8, 10),
	(9, 10),
	(10, 10),
	(11, 10) ON CONFLICT DO NOTHING;

INSERT INTO public.school_rating_components (id, key, label, weight, is_active, created_at, updated_at) VALUES
	(1, 'teaching_learning', 'Teaching & Learning', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(2, 'teacher_quality', 'Teacher Quality', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(3, 'student_development', 'Student Development', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(4, 'safety_wellbeing', 'Safety & Wellbeing', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(5, 'parent_experience', 'Parent Experience', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(6, 'transparency', 'Transparency', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(7, 'infrastructure', 'Infrastructure', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(8, 'sports_activities', 'Sports & Activities', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(9, 'career_guidance', 'Career Guidance', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(10, 'complaint_resolution', 'Complaint Resolution', 10.00, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44') ON CONFLICT DO NOTHING;

INSERT INTO public.teacher_rating_components (id, key, label, weight, is_active, created_at, updated_at) VALUES
	(1, 'subject_knowledge', 'Subject Knowledge', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(2, 'explanation', 'Explanation', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(3, 'communication', 'Communication', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(4, 'engagement', 'Engagement', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(5, 'fairness', 'Fairness', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(6, 'classroom_management', 'Classroom Management', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(7, 'individual_attention', 'Individual Attention', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(8, 'practical_learning', 'Practical Learning', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(9, 'feedback', 'Feedback', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(10, 'homework', 'Homework', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(11, 'student_support', 'Student Support', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44'),
	(12, 'punctuality', 'Punctuality', 8.33, true, '2026-10-09 21:18:44', '2026-10-09 21:18:44') ON CONFLICT DO NOTHING;

-- Move each id sequence past the explicit ids inserted above
SELECT setval(pg_get_serial_sequence('public.roles', 'id'), COALESCE((SELECT MAX(id) FROM public.roles), 1), (SELECT MAX(id) IS NOT NULL FROM public.roles));
SELECT setval(pg_get_serial_sequence('public.permissions', 'id'), COALESCE((SELECT MAX(id) FROM public.permissions), 1), (SELECT MAX(id) IS NOT NULL FROM public.permissions));
SELECT setval(pg_get_serial_sequence('public.states', 'id'), COALESCE((SELECT MAX(id) FROM public.states), 1), (SELECT MAX(id) IS NOT NULL FROM public.states));
SELECT setval(pg_get_serial_sequence('public.districts', 'id'), COALESCE((SELECT MAX(id) FROM public.districts), 1), (SELECT MAX(id) IS NOT NULL FROM public.districts));
SELECT setval(pg_get_serial_sequence('public.complaint_categories', 'id'), COALESCE((SELECT MAX(id) FROM public.complaint_categories), 1), (SELECT MAX(id) IS NOT NULL FROM public.complaint_categories));
SELECT setval(pg_get_serial_sequence('public.school_rating_components', 'id'), COALESCE((SELECT MAX(id) FROM public.school_rating_components), 1), (SELECT MAX(id) IS NOT NULL FROM public.school_rating_components));
SELECT setval(pg_get_serial_sequence('public.teacher_rating_components', 'id'), COALESCE((SELECT MAX(id) FROM public.teacher_rating_components), 1), (SELECT MAX(id) IS NOT NULL FROM public.teacher_rating_components));

COMMIT;
