#!/usr/bin/env bash
# Regenerates database/sql/01-schema.sql, 02-reference-data.sql and
# 03-demo-data.sql for PostgreSQL from the app's own migrations and seeders.
#
#   01  = the exact DDL `php artisan migrate` runs (`migrate --pretend`), plus
#         the `migrations` table pre-filled so a later `migrate --force` is a
#         no-op.
#   02  = rows written by the reference seeders (pg_dump --data-only).
#   03  = rows written by the demo seeders (pg_dump --data-only).
#
# Usage (from the repo root), against a dedicated, EMPTY scratch database:
#
#   createdb edu_sqlgen
#   DB_CONNECTION=pgsql DB_HOST=127.0.0.1 DB_PORT=5432 DB_DATABASE=edu_sqlgen \
#     DB_USERNAME=postgres DB_PASSWORD=... database/sql/generate.sh
#   dropdb edu_sqlgen
#
# Needs php, psql and pg_dump on PATH. The database is migrated and seeded
# by this script; it refuses to touch one that already has tables.
set -euo pipefail

cd "$(dirname "$0")/../.."
OUT=database/sql
: "${DB_DATABASE:?set DB_DATABASE to an empty scratch database}"
export DB_CONNECTION=pgsql PGHOST="${DB_HOST:-127.0.0.1}" PGPORT="${DB_PORT:-5432}" \
       PGUSER="${DB_USERNAME:-postgres}" PGPASSWORD="${DB_PASSWORD:-}" PGDATABASE="$DB_DATABASE"

REF_SEEDERS="RolesAndPermissionsSeeder LocationSeeder ComplaintCategorySeeder SchoolRatingComponentSeeder TeacherRatingComponentSeeder"
DEMO_SEEDERS="SchoolSeeder UserSeeder ComplaintSeeder FeedbackSeeder TeacherFeedbackSeeder RetaliationReportSeeder"
REF_TABLES="roles permissions role_has_permissions states districts complaint_categories school_rating_components teacher_rating_components"
DEMO_TABLES="schools school_profiles users model_has_roles officer_jurisdictions school_staff parent_profiles student_profiles teacher_profiles parent_school_relationships student_school_relationships teacher_school_relationships anonymous_identities complaints complaint_responses complaint_status_history complaint_resolutions school_feedback school_quality_scores teacher_feedback teacher_effectiveness_scores retaliation_reports"

psql_q() { psql -X -At -v ON_ERROR_STOP=1 -c "$1"; }

if [ "$(psql_q "select count(*) from information_schema.tables where table_schema = 'public'")" != "0" ]; then
  echo "Database $DB_DATABASE is not empty; use a fresh scratch database." >&2
  exit 1
fi

REV="$(git rev-parse --short HEAD)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- 01: schema --------------------------------------------------------------
# migrate --pretend prints each statement as " ⇂ <sql>" under its migration's
# name. It also creates the (empty) migrations table for real, as migrate does.
php artisan migrate --pretend --force --no-ansi > "$TMP/pretend.txt"
MIGRATIONS_DDL="$(php artisan tinker --no-ansi --execute 'foreach (DB::connection()->pretend(fn () => app("migration.repository")->createRepository()) as $q) echo $q["query"], ";", PHP_EOL;')"
TABLE_COUNT=$(( $(grep -c '^ ⇂ create table ' "$TMP/pretend.txt") + 1 ))

{
  cat <<EOF
-- =====================================================================
-- EDU (edutest.agtci.com) — 01-schema.sql   (PostgreSQL)
-- Full database schema: ${TABLE_COUNT} tables (incl. Laravel "migrations").
-- Generated by database/sql/generate.sh from the Laravel migrations @ ${REV}
-- with \`php artisan migrate --pretend\` — the exact SQL \`php artisan migrate\`
-- runs on PostgreSQL. Needs PostgreSQL 14+ (tested on 16).
--
-- HOW TO IMPORT into an EMPTY database (see database/sql/README.md):
--   psql -v ON_ERROR_STOP=1 -h <host> -U <user> -d <database> -f 01-schema.sql
-- or open it in pgAdmin's Query Tool on that database and run it.
-- No CREATE DATABASE here. Then import 02 (and optionally 03).
--
-- Runs in one transaction: on any error nothing is created.
-- The "migrations" table is filled at the end, so a later
-- \`php artisan migrate --force\` on the server is a no-op, not an error.
-- DO NOT import into a database that already has these tables.
-- =====================================================================

SET client_encoding = 'UTF8';
SET search_path = public;

BEGIN;

${MIGRATIONS_DDL}
EOF
  awk '
    /^ [0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{6}_[A-Za-z0-9_]+ / { printf "\n-- %s\n", $1; next }
    /^ ⇂ / { sub(/^ ⇂ /, ""); sub(/[ \t]+$/, ""); print $0 ";" }
  ' "$TMP/pretend.txt"
  echo
  echo "-- Record every migration as applied (batch 1)"
  echo 'INSERT INTO "migrations" ("migration", "batch") VALUES'
  grep -oE '^ [0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{6}_[A-Za-z0-9_]+' "$TMP/pretend.txt" \
    | sed -E "s/^ (.*)$/  ('\1', 1)/" | sed '$!s/$/,/;$s/$/;/'
  echo
  echo "COMMIT;"
} > "$OUT/01-schema.sql"

# --- data helpers ------------------------------------------------------------
# pg_dump's INSERT blocks only: drop its psql meta-commands (\restrict, which
# pgAdmin can't run), session SETs and comments, and its absolute setval()s,
# which are replaced by max(id)-based ones so a re-import never rewinds a
# sequence below rows added since.
dump_data() { # $1 = extra pg_dump flags, rest = tables
  local flags="$1"; shift
  # shellcheck disable=SC2086
  pg_dump --data-only --column-inserts --rows-per-insert=1000 --no-owner --no-privileges $flags \
    $(for t in "$@"; do printf -- '-t public.%s ' "$t"; done) \
    | grep -vE '^\\(un)?restrict |^SET |^SELECT pg_catalog\.(set_config|setval)\(|^--' \
    | cat -s
}
reset_sequences() { # tables
  echo "-- Move each id sequence past the explicit ids inserted above"
  for t in "$@"; do
    if [ -n "$(psql_q "select pg_get_serial_sequence('public.$t', 'id')" 2>/dev/null || true)" ]; then
      echo "SELECT setval(pg_get_serial_sequence('public.$t', 'id'), COALESCE((SELECT MAX(id) FROM public.$t), 1), (SELECT MAX(id) IS NOT NULL FROM public.$t));"
    fi
  done
}
count_rows() { psql_q "select count(*) from public.$1"; }

# --- 02: reference data ------------------------------------------------------
php artisan migrate --force --no-ansi > /dev/null
for s in $REF_SEEDERS; do php artisan db:seed --class="$s" --force --no-ansi > /dev/null; done
# shellcheck disable=SC2086
{
  cat <<EOF
-- =====================================================================
-- EDU — 02-reference-data.sql   (PostgreSQL)
-- Reference data every environment needs, generated by
-- database/sql/generate.sh from the app's own seeders @ ${REV}:
-- $(count_rows roles) roles, $(count_rows permissions) permissions + $(count_rows role_has_permissions) role grants (spatie),
-- $(count_rows states) states, $(count_rows districts) districts, $(count_rows complaint_categories) complaint categories, $(count_rows school_rating_components) school and
-- $(count_rows teacher_rating_components) teacher rating components.
-- Import AFTER 01-schema.sql into the same database. ON CONFLICT DO
-- NOTHING, so re-importing is harmless. Creates NO user accounts — see 03.
-- =====================================================================

SET client_encoding = 'UTF8';
SET search_path = public;

BEGIN;
EOF
  dump_data --on-conflict-do-nothing $REF_TABLES
  reset_sequences $REF_TABLES
  echo
  echo "COMMIT;"
} > "$OUT/02-reference-data.sql"

# --- 03: demo data -----------------------------------------------------------
for s in $DEMO_SEEDERS; do php artisan db:seed --class="$s" --force --no-ansi > /dev/null; done
# shellcheck disable=SC2086
{
  cat <<EOF
-- =====================================================================
-- EDU — 03-demo-data.sql   (PostgreSQL; OPTIONAL — TEST/STAGING ONLY)
-- The synthetic demo data from the app's seeders @ ${REV}, generated by
-- database/sql/generate.sh: $(count_rows users) users incl. every account in TEST_ACCOUNTS.md,
-- $(count_rows schools) schools, $(count_rows complaints) complaints, feedback, scores. All passwords = Password123!
-- (public, in this repo). NEVER import into a real production database.
-- Import AFTER 01 and 02, into an otherwise empty database.
-- =====================================================================

SET client_encoding = 'UTF8';
SET search_path = public;

BEGIN;
EOF
  dump_data "" $DEMO_TABLES
  reset_sequences $DEMO_TABLES
  echo
  echo "COMMIT;"
} > "$OUT/03-demo-data.sql"

# Every table the seeders wrote to must be in one of the two lists.
for t in $(psql_q "select table_name from information_schema.tables where table_schema = 'public' and table_type = 'BASE TABLE' and table_name <> 'migrations'"); do
  case " $REF_TABLES $DEMO_TABLES " in *" $t "*) continue ;; esac
  if [ "$(count_rows "$t")" != "0" ]; then
    echo "WARNING: seeders wrote to $t, which is in neither REF_TABLES nor DEMO_TABLES" >&2
  fi
done

echo "Wrote $OUT/01-schema.sql, 02-reference-data.sql, 03-demo-data.sql from $DB_DATABASE"
